apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
        environment: dev
        tier: backend
        department: engineering
      annotations:
        kubernetes.io/change-cause: "amigoscode/kubernetes:hello-world-v3"
    spec:
      containers:
      - name: hello-world
        image: amigoscode/kubernetes:hello-world-v3
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
